### ISSUE TITLE
D4-ToDo

### ISSUE THREAD

**Issue by angMaidt** [Dave89rr/GameVault#22]
`/`
- [x] Render games according to date released (most recent first)

`/collections/:collectionId`
- [x] Make drop down dynamic (displays our games)
- [x] When game is added, should add without re-rendering entire page
- [x] Edit Button should pull up form to edit collection name and desc
- [x] When edit is submitted, page should update without re-rendering entire page
- [x] Delete button for collection

`/users/:userId`
- [x] Formatting on profile page: 
  - [x] User info display 
  - [x] Footer currently hiding add new collection button

`/games/:gameId`
- [x] Game image rendering too large
- [x] Add to vault button => Add to collection
  - [x] Drop down with list of your collections
- [x] Set playedStatus
  - [x] Drop down menu

Frontend Javascripts
- [x] Duplicate games currently being rendered without being added to collection
- [x] Reviews should be added/edited/deleted dynamically
- [x] PlayedStatus should be dynamically updated on games

Reviews
- [x] Should be able to set rating for games
- [x] Should be able to edit review for game
- [x] Should be able to delete review for game

PlayedStatus
- [x] Should be dynamically updated for each game
- [x] User should be able to set played status from drop down on each game

vault-view.pug
Functionality added, however, done dynamically w/out redirects
- [x] Update edit button, when clicked should redirect to `/users/:userId/edit`, with edit form 
- [x] When edit is submitted, should redirect to `/users/:userId` with new changes

footer
- [x] Text clipping through

**Comment by angMaidt** [comment]
Bugs
- [ ] LoZ: OoT needs new image
- [ ] `/games/:gameId`
  - [ ] Add window.alert if game already in collection
  - [ ] When add to collection button hit, should pop up with options for which collection
  - [ ] User should only be able add single review for a game
- [ ] Some routes not protected, review and add requireAuth and csrfProtection (reviews routes)
- [ ] Logout button not in Nav (vault page)
- [ ] Favicon needs updating
- [ ] Generic styling
