### ISSUE TITLE
D5-ToDo

### ISSUE THREAD

**Issue by angMaidt** [Dave89rr/GameVault#24]
General
- [x] Some routes not protected, review and add requireAuth, csrfProtection (reviews routes)

PlayedStatus
- [x] When playedStatus is updated, it is changing the order of games in a collection

Reviews/Games
- [x] Edit and Delete buttons only show up on a new review after page has been refreshed
- [x] Average rating should appear next to game on `/games/:gameId`
- [ ] **Update ratings on reviews
- [x] User should only be able add single review for a game
- [x] After posting review textarea is not cleared

Collections
- [x] Need to implement DELETE
- [x] Collections should limit the number of games
- [x] Edit button in collection not currently hooked up
- [x] User should be able to dynamically delete games from collections
- [x] When game is added to collection, played status drop down does not appear until reset
 - [x] Add window.alert if game already in collection

404 Page
- [x] Should have one

Styling
- [x] Finalize logo/banner
- [x] Nav Bar styling
- [x] Logout needs styling
- [x] Finalize position for user info on `/users/:usersId`
- [x] Finalize position for add games button/drop down
- [x] Reviews needs styling 
- [x] Styling on user signup
  - [x] Formatting + more user icon options 
- [x] Favicon needs updating 
- [x] Edit user from textarea too big when not full screen
- [x] Logout button not in Nav (vault page)
